### ISSUE TITLE
npm start does not work on Windows

### ISSUE THREAD

**Issue by vmrvictor** [FacilMap/facilmap2#38] opened 2016-12-14 10:28 UTC
I have MySQL community version 6.3.7 (64 bits)
Node.js version v6.9.3
npm v3.10.9
code ELIFECYCLE

I tried at the beginning only to run (no changing the configuration of config.js), after that I had an error, so I created the schema facilmap, the user lifemap with password lifemap and updated the config.js file.
When running again npm start I get the following output:

npm ERR! Please include the following file with any support request:
npm ERR!     C:\internal\project\epmdtrpl\lib\facilmap2\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! facilmap2@0.0.1 start: `npm run deps && npm run build && npm run server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the facilmap2@0.0.1 start script 'npm run deps && npm run build && npm run server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the facilmap2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run deps && npm run build && npm run server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs facilmap2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls facilmap2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\internal\project\epmdtrpl\lib\facilmap2\npm-debug.log

[npm-debug.zip](https://github.com/FacilMap/facilmap2/files/651399/npm-debug.zip)

[config.zip](https://github.com/FacilMap/facilmap2/files/651400/config.zip)

**Comment by cdauth** [comment] 2016-12-14 11:51
Hey,

I haven’t used FacilMap on Windows and also do not have Windows to test it. But I suspect that the issue is simply caused by Windows not understanding the `&&` in the command.

Try to run these commands in a row:

```
npm update --dev
node node_modules\.bin\bower update
npm run build
```

This should set everything up. Then you can start FacilMap by running `npm run server`.

I will see whether I can fix it somehow so that you can run `npm start` on Windows in the future as well.

**Comment by vmrvictor** [comment] 2016-12-14 11:55
when running node node_modules\.bin\bower update I get an error:
C:\lib\facilmap2>node node_modules\.bin\bower update
C:\lib\facilmap2\node_modules\.bin\bower:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by cdauth** [comment] 2016-12-14 12:26
Strange, it seems like it is trying to run a linux script there.

Try to install bower globally and then run it:

```
npm install -g bower
bower update
```

**Comment by cdauth** [comment] 2017-03-04 17:31
This issue should be fixed after the restructuring into different sub-modules. Please re-open if it still occurrs.

**Closed by cdauth** 2017-03-04 17:31 UTC
Labels: bug

**Comment by yjh12** [comment] 2020-09-23 10:50
I want to ask what are the steps to deploy and install on Windows？thank you very much if you can tell me
